Fix setting correct connection on dumper instance
beyondcode/laravel-dump-server pull request #72
Opened 2020-10-23 10:50 UTC by BertvanHoekelen

https://github.com/beyondcode/laravel-dump-server/pull/70 introduces a bug where the connection would not be set on the `Dumper` class. This PR resolves that and also allows for custom bindings.

2020-10-27 08:58 UTC, Ilyes512 requested changes

2020-10-27 11:09 UTC, BertvanHoekelen commented on src/DumpServerServiceProvider.php
> +            $app->makeWith(Dumper::class, ['connection' => $connection])->dump($var);
I think it's added because the scope of `$this` in the callback is bound to the `VarDumper` instance.

2020-10-27 14:10 UTC, Ilyes512 commented on src/DumpServerServiceProvider.php
> +            $app->makeWith(Dumper::class, ['connection' => $connection])->dump($var);
No, `$this` is bound to the instance of `DumpServerServiceProvider`. I also tested it and it works.

> As of PHP 5.4.0, when declared in the context of a class, the current class is automatically bound to it, making $this available inside of the function's scope. If this automatic binding of the current class is not wanted, then static anonymous functions may be used instead.

https://www.php.net/manual/en/functions.anonymous.php

2020-10-27 15:03 UTC, BertvanHoekelen commented on src/DumpServerServiceProvider.php
> +            $app->makeWith(Dumper::class, ['connection' => $connection])->dump($var);
Yeah, I thought it was added [here](https://github.com/beyondcode/laravel-dump-server/pull/70/files#diff-790474338c5780f6835df0b22b7cdef0acad97843bbb01007cce30360cb90bb7R53) for a reason. Could have been that the handler was called with a [`bindTo`](https://www.php.net/manual/en/closure.bindto.php). Didn't check it further. But thanks for the suggestions, will commit them.

2020-11-12 01:41 UTC, BertvanHoekelen commented
Don't want to be rude 😊 but @mpociot when you have time.

2020-12-15 10:57 UTC, merged

2020-12-15 10:57 UTC, mpociot commented
Thank you and sorry for the delay